typography_spectrum: 0.2795884497463703
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.015618076082319021
  lightness: 0.5205656564794481
  saturation: 0.5855060385074466
  rhythmicContrast: 0.61797143984586
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.23900216654874384
analytics:
  google: null
  facebook: null
  twitter: null
name: ohb
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: orange haired boy
purpose: []
